AWSTemplateFormatVersion: 2010-09-09

Description: Creating IAM Role with Instance Profile

Resources:

  Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      Policies:
        -
          PolicyName: Policy
          PolicyDocument:
            Statement:
              -
                Effect: Allow
                Action: "*"
                Resource:
                  - "*"

  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - !Ref Role


Outputs:
  IAMRoleARN:
    Description: IAM Role ARN
    Value: 
      !GetAtt Role.Arn
    Export:
      Name: !Sub ${AWS::StackName}-RoleArn

  InstanceProfileArn:
    Description: Instance Profile ARN
    Value: 
      !Ref InstanceProfile
    Export:
      Name: !Sub ${AWS::StackName}-InstanceProfile

