AWSTemplateFormatVersion : 2010-09-09

Description : Creates a full stack for DocumentService

# Metadata section for ct template.
Metadata:
  Name: DocumentService
  Version: 1.1.2

# Parameters section for ct template.
Parameters:

  BastionSecurityGroup:
    Description: Provide Bastion Security Group
    Type: AWS::EC2::SecurityGroup::Id
    Default: sg-0816ce73

  CODEVERSION:
    Description: CodeVersion
    Type: String
    Default: 1.2.16

  COMPONENT:
    Description: Environment
    Type: String
    Default: ws

  ENV:
    Description: Environment
    Type: String
    Default: qal

  ELBSubnets:
    Description: The KeyName associated Instance
    Type: List<AWS::EC2::Subnet::Id>
    Default: "subnet-5e43f317,subnet-8f6af4e8"

  ELBCidrIp:
    Description: Provice a list of CidrIp ranges that are allowed for ELB
    Type: CommaDelimitedList
    Default: "0.0.0.0/0,1.1.1.1/24"

  Endpoint:
    Description: Email address for Alarm Notification
    Type: String
    Default: "santhoshdeepu_patrayuni@intuit.com"

  Hosttag:
    Description: Host Tag
    Type: String
    Default: "ngwi-qa-1"

  HostedZone:
    Description: Provide the Hosted Zone Name
    Type: String
    Default: "learn.intuit.net."

  HostedZoneId:
    Description: Provide the Hosted Zone HostedZoneId
    Type: AWS::Route53::HostedZone::Id
    Default: Z148YSNYOMPNX9

  ImageId:
    Description: The AMIID for Instance
    Type: AWS::EC2::Image::Id
    Default: ami-6f46da0f

  InstanceType:
    Description: The InstanceType of Instance
    Type: String
    Default: t2.micro

  KeyName:
    Description: The KeyName associated Instance
    Type: AWS::EC2::KeyPair::KeyName
    Default: IntuitKey_Personal

  MaxSize:
    Description: MaxSize of Instance
    Type: Number
    Default: 2

  MinSize:
    Description: MinSize of Instance
    Type: Number
    Default: 1

  ScalingAdjustmentUp:
    Description: Scaling Adjustment for addition
    Type: Number
    Default: 1

  ScalingAdjustmentDown:
    Description: Scaling Adjustment for reduction
    Type: Number
    Default: -1

  SERVICE:
    Description: ServiceName
    Type: String
    Default: fdpdocv2

  VpcId:
    Description: Provide Current VPC ID
    Type: AWS::EC2::VPC::Id
    Default: vpc-583f7f3f

# Coniditions Section


# Resources Section

Resources:

  SNSStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "https://s3-us-west-2.amazonaws.com/psd8/SNSTopic.template"
      TimeoutInMinutes: 5
      Parameters:
        TopicName:
          Ref: Hosttag
        Endpoint:
          Ref: Endpoint

  InstanceSecurityGroupStack :
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL : "https://s3-us-west-2.amazonaws.com/psd8/InstanceSecurityGroup.template"
      TimeoutInMinutes : 5
      Parameters:
        VpcId: 
          Ref : VpcId
        BastionSG:
          Ref : BastionSecurityGroup
        SGName:
          Ref: Hosttag

  ELBStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "https://s3-us-west-2.amazonaws.com/psd8/ELB.template"
      TimeoutInMinutes : 5
      Parameters:
        VpcId: 
          Ref : VpcId
        SGName:
          Ref: Hosttag
        ELBCidrIp:
          !Join [",",!Ref ELBCidrIp]
        ELBSubnets:
          !Join [",",!Ref ELBSubnets]
        InstanceSG:
          !GetAtt InstanceSecurityGroupStack.Outputs.InstanceSG

  RecordSetCreationStack:
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: "https://s3-us-west-2.amazonaws.com/psd8/Route53_RecordSet.template"
      TimeoutInMinutes: 5
      Parameters:
        ELBDNSName:
          !GetAtt ELBStack.Outputs.ELBDNSName
        CODEVERSION:
          Ref: CODEVERSION
        COMPONENT:
          Ref: COMPONENT
        ENV:
          Ref: ENV
        SERVICE:
          Ref: SERVICE
        HostedZone:
          Ref: HostedZone
        HostedZoneId:
          Ref: HostedZoneId

  AutoScalingStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "https://s3-us-west-2.amazonaws.com/psd8/AutoScaling.template"
      TimeoutInMinutes: 10
      Parameters:
        CODEVERSION:
          Ref: CODEVERSION
        COMPONENT:
          Ref: COMPONENT
        ENV:
          Ref: ENV
        SERVICE:
          Ref: SERVICE
        InstanceSG:
          !GetAtt InstanceSecurityGroupStack.Outputs.InstanceSG
        PublicELB:
          !GetAtt ELBStack.Outputs.PublicELB
        SNSTopicARN:
          !GetAtt SNSStack.Outputs.SNSTopicARN
        Hosttag:
          Ref: Hosttag
        MinSize:
          Ref: MinSize
        MaxSize:
          Ref: MaxSize
        ImageId:
          Ref: ImageId
        InstanceType:
          Ref: InstanceType
        KeyName:
          Ref: KeyName
        ScalingAdjustmentUp:
          Ref: ScalingAdjustmentUp
        ScalingAdjustmentDown:
          Ref: ScalingAdjustmentDown
        VPCZoneIdentifier:
          !Join [",",!Ref ELBSubnets]

  AutoScalingAlarm:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "https://s3-us-west-2.amazonaws.com/psd8/AutoScaling_Alarm.template"
      TimeoutInMinutes: 5
      Parameters:
        AutoScalingGroup:
          !GetAtt AutoScalingStack.Outputs.AutoScalingGroup
        SNSTopicARN:
          !GetAtt SNSStack.Outputs.SNSTopicARN
        ScaleUpPolicy:
          !GetAtt AutoScalingStack.Outputs.ScaleUpPolicy
        ScaleDownPolicy:
          !GetAtt AutoScalingStack.Outputs.ScaleDownPolicy



Outputs:

  InstanceSG:
    Description: Instance Security Group
    Value:
      !GetAtt InstanceSecurityGroupStack.Outputs.InstanceSG

  PublicELB:
    Description: Public ELB
    Value:
      !GetAtt ELBStack.Outputs.PublicELB

  ELBDNSName:
    Description: ELB DNS Name
    Value:
      !GetAtt ELBStack.Outputs.ELBDNSName

  ELBSecurityGroup:
    Description: ELB Security Group Id
    Value:
      !GetAtt ELBStack.Outputs.ELBSecurityGroup

  SNSTopicName:
    Description: Name of the Security Group Name
    Value:
      !GetAtt SNSStack.Outputs.SNSTopicName

  SNSTopicARN:
    Description: SNS Topic ARN
    Value:
      !GetAtt SNSStack.Outputs.SNSTopicARN

  AutoScalingLaunchConfiguration:
    Description: AutoScaling Launch Configuration
    Value:
      !GetAtt AutoScalingStack.Outputs.AutoScalingLaunchConfiguration

  AutoScalingGroup:
    Description: AutoScaling Group
    Value:
      !GetAtt AutoScalingStack.Outputs.AutoScalingGroup

  ScaleUpPolicy:
    Description: Scale up Policy
    Value: 
      !GetAtt AutoScalingStack.Outputs.ScaleUpPolicy

  ScaleDownPolicy:
    Description: Scale down Policy
    Value:
      !GetAtt AutoScalingStack.Outputs.ScaleDownPolicy

  RecordSetInfo:
    Description: New RecordSet created
    Value:
      !GetAtt RecordSetCreationStack.Outputs.RecordSetName





