Resources:
  BaseInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
      - Ref: BaseInstanceRole

  BaseInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action:
          - sts:AssumeRole
          Effect: Allow
          Principal:
            Service:
            - ec2.amazonaws.com
        Version: '2012-10-17'
      Path: /

  RolePolicies:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: root
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action: "*"
          Resource: "*"
      Roles:
      - !Ref BaseInstanceRole

  ASLG:
    Type: "AWS::AutoScaling::LaunchConfiguration"
    Metadata:
      AWS::CloudFormation::Init:
        configSets:
          Test : 
            - "Install"
            - "Configure"
#            - "VerifyELB"
        Install:
          packages:
            yum:
              curl: []
              lvm2: []
              ntp: []
              rsync: []
              screen: []
              telnet: []
              wget: []
              httpd: []
        Configure:
          files:
            /var/www/html/index.html:
              content: !Join
                - ''
                - - '<h1>My Name is Santhosh Deepu Patrayuni.</h1>'
              mode: '0755'
              owner: root
              group: root
          services: 
            sysvinit: 
              httpd: 
                enabled: "true"
                ensureRunning: "true"
                files: 
                  - "/etc/httpd/conf/httpd.conf"
                sources: 
                  - "/var/www/html"
    Properties:
      ImageId: ami-6f46da0f
      InstanceType: t2.micro
      KeyName: intuit_learning
      SecurityGroups:
        - sg-c6f88bbd
        - sg-d0e794ab
#        - !Ref ELBtoEC2Ingress
      IamInstanceProfile:
        !Ref BaseInstanceProfile
      UserData:
        Fn::Base64:
          Fn::Join:
            - ''
            - - '#!/bin/bash -v'
              - 'export PATH=$PATH:/opt/aws/bin'
              - '#Download rpm from s3'
              - 'aws s3 cp '
              - 's3://psd8/ELB.template'
              - ' /root/'

              - 'cfn-init -v --stack=${AWS::StackName} --resource=ASLG --configsets=Test --region=${AWS::Region}'
              - 'cfn-signal --stack=${AWS::StackName} --resource=ASAG --region=${AWS::Region}'

  ASAG:
    Type: "AWS::AutoScaling::AutoScalingGroup"
    Properties:
      LaunchConfigurationName: !Ref ASLG
      MaxSize: '1'
      MinSize: '1'
      Tags:
        - Key: Name
          Value: ASwithELBVerify4
          PropagateAtLaunch: true
      VPCZoneIdentifier:
        - subnet-81d796e6
        - subnet-3aed7673
    CreationPolicy:
      ResourceSignal:
        Timeout: PT10M