AWSTemplateFormatVersion : 2010-09-09

Description : "Single EC2 instance template"

Parameters:
  StackName:
    Description: Provice the Stack StackName
    Type: String

Resources:
  SQLEBSVolume:
      Type: "AWS::EC2::Volume"
      Properties:
        AvailabilityZone: 
          !Select [0, !GetAZs "us-west-2"]
        Encrypted: true
        Iops: 1000
        Size: 100
        Tags:
          - Key: Name
            Value: SQLEBSVolume
        VolumeType: io1
      DeletionPolicy: "Snapshot"

  SQLEBSAttach:
      Type: "AWS::EC2::VolumeAttachment"
      Properties:
        Device: /dev/xvdz
        InstanceId: 
          Fn::ImportValue: 
            !Sub ${StackName}-SQLEC2
        VolumeId: !Ref SQLEBSVolume