AWSTemplateFormatVersion : 2010-09-09

Description : "Single EC2 instance template"

Parameters:
  Iops: 
    Description: Provide the IOPS Value
    Type: Number

  AZ:
    Description: Provide the AvailabilityZone
    Type: String

Resources:
  SQLEBSVolume:
    Type: "AWS::EC2::Volume"
    Properties:
      AvailabilityZone: !Ref AZ
      Encrypted: true
      Iops: !Ref Iops
      Size: 100
      Tags:
        - Key: Name
          Value: SQLEBSVolume
      VolumeType: io1
    DeletionPolicy: "Snapshot"

Outputs:
  SBGEBSVolume:
    Description: SQL EC2 Instance created
    Value:
      Ref: SQLEBSVolume
    Export:
      Name: 
        !Sub ${AWS::StackName}-SQLEBSVolume


