AWSTemplateFormatVersion: 2010-09-09

Description: Nested Main Template

Parameters: 
  AMI : 
    Description: Provide ImageId
    Type: AWS::EC2::Image::ImageId
    Default: ami-6f46da0f

Resources:
  PSDInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: 
        Ref: AMI
      InstanceType: t2.micro
      KeyName: IntuitKey_Personal
      SubnetId: subnet-5e43f317
      SecurityGroupIds:
      - Ref: SG
      Tags:
      - Key: Name
        Value: PSD